import glamora from './glamora.svg';
import starsRight from './beranda/stars-right.svg';
import starsLeft from './beranda/stars-left.svg';
import faceBeranda from './beranda/face-beranda1.png';
import macbook from './beranda/macbook.png';
import calendar from './beranda/calendar.svg';
import ellipse from './beranda/ellipse.svg';
import health from './beranda/health.svg';
import shapes from './beranda/shapes.svg';
import line1Beranda from './beranda/line-rekomendasi.png';
import line2Beranda from './beranda/line-bentuk-wajah.png';
import line3Beranda from './beranda/line-usia-kulit.png';
import ellipseAnalisis from './beranda/ellipse-analisis-wajah.svg';
import aboutBeranda from './beranda/about.png';
import starFeature from './beranda/star-features.svg';
import analisisGif from './beranda/analisis-gif.gif';
import progressGif from './beranda/progress-gif.gif';
import virtualGif from './beranda/virtual-gif.gif';
import arrowRight from './beranda/arrow-right.svg';
import faceInMirror from './beranda/face-in-mirror.png';

export { faceInMirror, arrowRight, virtualGif, progressGif, analisisGif, starFeature, aboutBeranda, glamora, starsRight, starsLeft, faceBeranda, macbook, calendar, ellipse, health, shapes, line1Beranda, line2Beranda, line3Beranda, ellipseAnalisis };